server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: HomestayDev
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=HomestayDev;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;useUnicode=true;characterEncoding=UTF-8
    username: j2ee
    password: Minh@7979
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        connection:
          charSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangminh.p7979@gmail.com
    password: iwakdvxmmnwmutgs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/HomestayRealm
          jwk-set-uri: http://localhost:8080/realms/HomestayRealm/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8080/
  realm: HomestayRealm
  client-id: homestay-client
  client-secret: U6IpDXlqMwRODktPk3usOM8gODXY9YJI

vnpay:
  tmn-code: 7GNDMSBK
  hash-secret: SL5ZVQYVP56C3818K450D3AOQXQ3XBY0
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:9999/api/payment/vnpay-return
